name = "corpnce-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "corpnce-website"
routes = [
  { pattern = "corpnce.com", zone_name = "corpnce.com" },
  { pattern = "www.corpnce.com", zone_name = "corpnce.com" }
]